service: wanjun-pythonhttpapi-assignment
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  profile: default
  stackName: wanjun-pyhttpapi

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
